declare module '@babel/core' {}
declare module '@babel/generator' {}
declare module '@babel/template' {}
declare module '@babel/traverse' {}
declare module 'connect' {}
declare module 'debug' {}
declare module 'diff-match-patch' {}
declare module 'estree' {}
declare module 'graceful-fs' {}
declare module 'istanbul-lib-coverage' {}
declare module 'istanbul-lib-report' {}
declare module 'istanbul-reports' {}
declare module 'json-schema' {}
declare module 'json5' {}
declare module 'lodash' {}
declare module 'ms' {}
declare module 'node-fetch' {}
declare module 'node-forge' {}
declare module 'stack-utils' {}
declare module 'uuid' {}
declare module 'ws' {}
declare module 'yargs' {}
declare module 'yargs-parser' {}
